---
- hosts: all

  tasks:
    - name: prepare a directory
      file: path=~/.lein/bin state=directory

    - name: download the script
      get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=~/.lein/bin mode=0755