---
- hosts: all
  vars:
    mew_version: 6.8

  tasks:
    - name: install required packages
      apt:
        name: ['stunnel4', 'w3m', 'wv']
        state: latest
        update_cache: yes
      become: yes

    - name: download the tarball
      get_url: url=http://mew.org/Release/mew-{{ mew_version }}.tar.gz
               dest=/home/{{ ansible_user_id }}/Downloads

    - name: extract it
      command: tar xzf /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}.tar.gz
      args:
        chdir: /home/{{ ansible_user_id }}/Downloads
        creates: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}

    - name: configure
      command: ./configure
      args:
        chdir: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}
        creates: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}/Makefile

    - name: make clean
      command: make clean
      args:
        chdir: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}

    - name: make
      command: make
      args:
        chdir: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}
        creates: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}/mew.elc

    - name: make install
      command: make install
      args:
        chdir: /home/{{ ansible_user_id }}/Downloads/mew-{{ mew_version }}
      become: yes

    - name: place a configuration file
      copy: src=dot-mew.el dest=/home/{{ ansible_user_id }}/.mew.el
