---
- hosts: all

  tasks:
    - name: install required packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - chromium-browser
        - nautilus-dropbox
        - tmux
        - git
        - pass
        - ansible
        - davfs2
        - exfat-fuse
        - screen
        - flashplugin-installer
        - gnome-sound-recorder
      sudo: yes

    - name: use customized keyborad definition
      copy: src=keyboard.dvorak dest=/etc/default/keyboard
      sudo: yes

    - name: copy my tmux configuration
      copy: src=tmux.conf dest=~/.tmux.conf

    - name: clone password store from repository
      git: repo=https://github.com/hamazy/passstore.git
           dest=~/.password-store

- include: emacs.yml
- include: mew.yml
- include: emacs-w3m.yml
- include: skk.yml
- include: skype.yml
- include: java.yml
- include: japanese.yml
- include: git.yml
- include: gtags.yml
- include: lein.yml
- include: asciidoc.yml
- include: haskell.yml
- include: virtualbox.yml
- include: vagrant.yml
- include: eclipse.yml