---
- hosts: all

  tasks:
    - name: download deb package
      get_url: url=https://dl.bintray.com/mitchellh/vagrant/vagrant_1.7.4_x86_64.deb dest=~/

    - name: install the package
      apt: deb=/home/{{ ansible_ssh_user }}/vagrant_1.7.4_x86_64.deb state=installed
      sudo: yes